---
kind: pipeline
type: kubernetes
name: cnj-tracing-build

steps:
  - name: micro-commit-stage
    image: docker.cloudtrain.aws.msgoat.eu/cloudtrain/cnj-drone-build:2.0.2
    privileged: true
    commands:
      - start-docker.sh
      - mvn clean install -f pom.xml -B -ff -e -V -U -P commit-stage -Dchangelist=.${DRONE_BRANCH} -Dsha1=.${DRONE_COMMIT_SHA:0:8} -Dsonar.login=$SONARQUBE_TOKEN -Djacoco.skip=true
    environment:
      SONARQUBE_TOKEN:
        from_secret: sonarqube_token
  - name: micro-integration-test-stage
    image: docker.cloudtrain.aws.msgoat.eu/cloudtrain/cnj-drone-build:2.0.2
    privileged: true
    commands:
      - start-docker.sh
      - mvn clean verify -f pom.xml -B -ff -e -V -U -P integration-test-stage -Dchangelist=.${DRONE_BRANCH} -Dsha1=.${DRONE_COMMIT_SHA:0:8}
